/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationText: typeof import('./components/common/AnimationText.vue')['default']
    ArtPlayer: typeof import('./components/player/ArtPlayer.vue')['default']
    ChannelInfo: typeof import('./components/ChannelInfo.vue')['default']
    DropdownSelect: typeof import('./components/common/DropdownSelect.vue')['default']
    FloatTool: typeof import('./components/FloatTool.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconGithub: typeof import('./components/icon/IconGithub.vue')['default']
    LoadingIndicator: typeof import('./components/common/LoadingIndicator.vue')['default']
    LoadingIndicatorImage: typeof import('./components/common/LoadingIndicatorImage.vue')['default']
    LucideArrowDown: typeof import('@lucide/vue')['ArrowDown']
    LucideArrowDown10: typeof import('@lucide/vue')['ArrowDown10']
    LucideArrowUp: typeof import('@lucide/vue')['ArrowUp']
    LucideArrowUp01: typeof import('@lucide/vue')['ArrowUp01']
    LucideCalendarClock: typeof import('@lucide/vue')['CalendarClock']
    LucideChevronDown: typeof import('@lucide/vue')['ChevronDown']
    LucideClock: typeof import('@lucide/vue')['Clock']
    LucideEye: typeof import('@lucide/vue')['Eye']
    LucideEyeOff: typeof import('@lucide/vue')['EyeOff']
    LucideGripVertical: typeof import('@lucide/vue')['GripVertical']
    LucideHistory: typeof import('@lucide/vue')['History']
    LucideLayoutGrid: typeof import('@lucide/vue')['LayoutGrid']
    LucideLayoutList: typeof import('@lucide/vue')['LayoutList']
    LucideMenu: typeof import('@lucide/vue')['Menu']
    LucideRefreshCw: typeof import('@lucide/vue')['RefreshCw']
    LucideRss: typeof import('@lucide/vue')['Rss']
    LucideSlidersHorizontal: typeof import('@lucide/vue')['SlidersHorizontal']
    LucideTag: typeof import('@lucide/vue')['Tag']
    LucideVideo: typeof import('@lucide/vue')['Video']
    LucideX: typeof import('@lucide/vue')['X']
    NewsGridItem: typeof import('./components/news/NewsGridItem.vue')['default']
    NewsGridView: typeof import('./components/news/NewsGridView.vue')['default']
    NewsListItem: typeof import('./components/news/NewsListItem.vue')['default']
    NewsListView: typeof import('./components/news/NewsListView.vue')['default']
    RssInfo: typeof import('./components/RssInfo.vue')['default']
    SettingPanel: typeof import('./components/SettingPanel.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SidebarContent: typeof import('./components/SidebarContent.vue')['default']
    Switch: typeof import('./components/common/Switch.vue')['default']
    Tabs: typeof import('./components/common/Tabs.vue')['default']
    TagList: typeof import('./components/TagList.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
  }
}
